apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django-app
          image: django-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "DjangoApp.settings"
            - name: STATIC_ROOT
              value: "/app/static/"
          command:
            [
              "sh",
              "-c",
              "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000",
            ]
